CREATE TABLE author ( 
	id integer generated by default as identity primary key, 
	authorName varchar(50) NOT NULL

);


CREATE TABLE book ( 
	id integer generated by default as identity primary key, 
	bookName varchar(250) NOT NULL 
);



CREATE TABLE author_book ( 
	bookId integer NOT NULL, 
	authorId integer NOT NULL, 
	PRIMARY KEY (authorId,bookId), 
	CONSTRAINT book_key FOREIGN KEY (bookId) REFERENCES book (id), 
	CONSTRAINT author_key FOREIGN KEY (authorId) REFERENCES author (id) 
);

ALTER TABLE author_book
DROP FOREIGN KEY book_key;

drop table author_book;
drop table book;
drop table author;


select * from AUTHOR;

insert into author (authorName) values('Andre');
insert into author (authorName) values('Tore');
insert into author (authorName) values('KIM');

insert into book (bookName) values('DassBoka');
insert into book (bookName) values('Trist Som Faen');
insert into book (bookName) values('Doppler');

insert into AUTHOR_BOOK values(1,1);
insert into AUTHOR_BOOK values(1,2);
insert into AUTHOR_BOOK values(1,3);

delete from AUTHOR_BOOK where AUTHOR_BOOK.AUTHORID = 3;  

select * from AUTHOR_BOOK;
select distinct b.bookName, a.authorName, a.id as superid from  BOOK b, AUTHOR a, AUTHOR_BOOK ab where ab.AUTHORID = 1;